version: '3.3'

services:
  vscode:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: "3.1"
        INSTALL_NODE: "false"
        NODE_VERSION: "lts/*"
        INSTALL_AZURE_CLI: "false"

    environment:
      ENVIRONMENT: "devcontainer"

    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/workspace:cached
      # Forwards the local Docker socket to the container.
      - /var/run/docker.sock:/var/run/docker-host.sock 

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity 

  sqlserver:
    image: microsoft/mssql-server-linux:2017-latest
    ports:
      - "1433:1433"
    restart: always
    environment:
      SA_PASSWORD: "Au3aFCz0xsLTKxy"
      ACCEPT_EULA: "Y"

  seq:
    image: datalust/seq:latest
    environment:
    - ACCEPT_EULA=Y
    ports:
    - "5341:5341"
    - "5080:80"
    restart: always
